export const TITLE = 'udemy-nextjs-microblog-for-beginner';

export const DESCRIPTION = 'Generated by create next app';

export const NAME = 'etranger2268';

export const PROFILE = `私はフロントエンドエンジニアです。
  Next.jsを勉強しています。`;
